"""
Correlation models — AttackChain and supporting types.
"""

import uuid
from dataclasses import dataclass, field
from typing import Optional

from packetiq.detection.models import DetectionEvent, Severity


# Lockheed Martin Cyber Kill Chain phases (ordered)
KILL_CHAIN_PHASES = [
    "Reconnaissance",
    "Weaponization",
    "Delivery",
    "Exploitation",
    "Installation",
    "Command & Control",
    "Actions on Objectives",
]


@dataclass
class MitreTechnique:
    tactic_id:      str   # e.g. "TA0043"
    tactic_name:    str   # e.g. "Reconnaissance"
    technique_id:   str   # e.g. "T1046"
    technique_name: str   # e.g. "Network Service Discovery"

    def __str__(self) -> str:
        return f"{self.technique_id} — {self.technique_name} [{self.tactic_name}]"

    def __hash__(self):
        return hash(self.technique_id)

    def __eq__(self, other):
        return isinstance(other, MitreTechnique) and self.technique_id == other.technique_id


@dataclass
class AttackChain:
    """
    A correlated group of DetectionEvents that together describe a
    multi-stage attack pattern or threat actor behaviour.
    """
    chain_id:   str   = field(default_factory=lambda: str(uuid.uuid4())[:8].upper())
    name:       str   = ""
    description: str  = ""

    # Who and what
    attacker_ips: set  = field(default_factory=set)
    target_ips:   set  = field(default_factory=set)
    events:       list = field(default_factory=list)   # list[DetectionEvent]

    # Scoring
    severity:   Severity = Severity.MEDIUM
    confidence: float    = 0.5

    # Timeline
    first_seen: float = 0.0
    last_seen:  float = 0.0

    # Threat intelligence
    mitre_techniques:    list = field(default_factory=list)  # list[MitreTechnique]
    kill_chain_phases:   list = field(default_factory=list)  # list[str]
    primary_phase:       str  = ""                           # highest-stage phase

    # Human-readable narrative generated by rules
    analyst_note: str = ""

    # ── Computed properties ─────────────────────────────────────────────

    @property
    def event_count(self) -> int:
        return len(self.events)

    @property
    def duration(self) -> float:
        return max(0.0, self.last_seen - self.first_seen)

    @property
    def unique_tactics(self) -> list[str]:
        seen = []
        for t in self.mitre_techniques:
            if t.tactic_name not in seen:
                seen.append(t.tactic_name)
        return seen

    @property
    def unique_technique_ids(self) -> list[str]:
        return list({t.technique_id for t in self.mitre_techniques})

    def absorb(self, other: "AttackChain"):
        """Merge another chain's events and intel into this one in-place."""
        self.events = _deduplicate_events(self.events + other.events)
        self.attacker_ips |= other.attacker_ips
        self.target_ips   |= other.target_ips

        existing_ids = {t.technique_id for t in self.mitre_techniques}
        for t in other.mitre_techniques:
            if t.technique_id not in existing_ids:
                self.mitre_techniques.append(t)
                existing_ids.add(t.technique_id)

        for ph in other.kill_chain_phases:
            if ph not in self.kill_chain_phases:
                self.kill_chain_phases.append(ph)

        if self.events:
            self.first_seen = min(e.timestamp for e in self.events if e.timestamp)
            self.last_seen  = max(e.timestamp for e in self.events if e.timestamp)

        # Take higher severity
        sev_order = {Severity.CRITICAL: 0, Severity.HIGH: 1,
                     Severity.MEDIUM: 2, Severity.LOW: 3}
        if sev_order.get(other.severity, 9) < sev_order.get(self.severity, 9):
            self.severity = other.severity

        self.confidence = max(self.confidence, other.confidence)
        self._update_primary_phase()

    def _update_primary_phase(self):
        """Primary phase = the latest kill chain stage present."""
        for phase in reversed(KILL_CHAIN_PHASES):
            if phase in self.kill_chain_phases:
                self.primary_phase = phase
                return


def _deduplicate_events(events: list) -> list:
    """Deduplicate events by identity (object id), preserving order."""
    seen_ids = set()
    result = []
    for e in events:
        eid = id(e)
        if eid not in seen_ids:
            seen_ids.add(eid)
            result.append(e)
    return result
